version: "3.9"

services:
  fastapi:
    build: ParserApp
    command: bash -c "python -m uvicorn app:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./ParserApp:/app
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

