version: "3.9"

services:
  fastapi:
    build: src
    command: bash -c "python -m uvicorn app:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    env_file:
      - env/backends.env
      - env/twitch.env
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  zookeeper:
    image: 'zookeeper:3.6.3'
    ports:
      - '2181:2181'
  kafka:
    image: 'bitnami/kafka:3.0.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
